connector.name=iceberg
iceberg.catalog.type=nessie
iceberg.nessie.uri=http://nessie:19120/api/v1
iceberg.nessie.ref=main
iceberg.nessie.default-warehouse=gs://${ENV:GCS_BUCKET}/warehouse
iceberg.file-io-impl=org.apache.iceberg.gcp.gcs.GCSFileIO
