connector.name=iceberg
iceberg.catalog.type=nessie
iceberg.nessie-catalog.uri=http://nessie:19120/api/v2
iceberg.nessie-catalog.ref=main
iceberg.nessie-catalog.default-warehouse-dir=gs://${ENV:GCS_BUCKET}/warehouse
fs.native-gcs.enabled=true
gcs.json-key-file-path=/tmp/gcs/gcs-key.json
